name: wasm-deploy

on:
  push:
    branches:
      - master
      - 0.*

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run:
          cd web &&
          wasm-pack build ".." --target web --out-name web --out-dir ./web/pkg &&
          mkdir dist &&
          npm ci && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist
          force_orphan: true
